baseURL = "https://deee.dev/"
languageCode = "en-us"
title = "dee's thoughts"
theme = "solar-theme-hugo"

[params]
  scheme = "preference" # light, dark, gray or preference
  description = "baby's first blog"
  custom_css = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = "Feed"
    url = "https://deee.dev/posts/"
  [[menu.main]]
    name = "Repository"
    url = "https://github.com/dl-watson/dee-thoughts"