baseURL = "http://deee.dev/"
languageCode = "en-us"
title = "dee's thoughts"
theme = "solar-theme-hugo"


[params]
  scheme = "preference" # light, dark, gray or preference
  description = "baby's first blog"

[menu]
  [[menu.main]]
    name = "Feed"
    url = "/index.xml"
  [[menu.main]]
    name = "Repository"
    url = "https://github.com/bake/solar-theme-hugo/"
  [[menu.other]]
    name = "Hugo"
    url = "https://themes.gohugo.io/solar-theme-hugo/"
  [[menu.other]]
    name = "Demo"
    url = "https://themes.gohugo.io/theme/solar-theme-hugo/"